services: 
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: 
      - .env
    depends_on:
      - minio
      - postgres
    ports:
      - "6000:6000"
  minio:
    container_name: minio
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: minioadmin 
      MINIO_ROOT_PASSWORD: minioadmin
      STORAGE_PORT: 9090
  postgres:
    container_name: db
    image: postgres:15.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
